In [1]:
def flatten(x):
    try:
        it = iter(x)
    except TypeError:
        yield x
    else:
        for i in it:
            for j in flatten(i):
                yield j

import pandas as pd
import itertools
data=[]
curr_sample = [120,300,0,0,0,15,30,8000,0,0,30,6,list(itertools.chain.from_iterable(itertools.repeat(x, 20) for x in [0]))]
data.append(list(flatten(curr_sample)))
curr_sample = [90,360,0,0,0,18,28,7500,0,0,15,8,list(itertools.chain.from_iterable(itertools.repeat(x, 20) for x in [0]))]
data.append(list(flatten(curr_sample)))
curr_sample = [100,400,0,0,0,20,20,7000,0,0,50,10,list(itertools.chain.from_iterable(itertools.repeat(x, 20) for x in [0]))]
data.append(list(flatten(curr_sample)))
curr_sample = [150,210,0,0,0,17,28,6500,0,0,60,5,list(itertools.chain.from_iterable(itertools.repeat(x, 20) for x in [0]))]
data.append(list(flatten(curr_sample)))
curr_sample = [180,380,0,0,0,24,20,7000,0,0,80,10,list(itertools.chain.from_iterable(itertools.repeat(x, 20) for x in [0]))]
data.append(list(flatten(curr_sample)))
df = pd.DataFrame(data=data,columns=['T_prem','T_gen','N_pot_t','M_kub_t','C_kub_t','N_pod_L','M_kub_L','C_kub_L','U_type','r','T_delay_pr','nr_m','Up_rpbar_less_rp_count','sum_PID','Pk_sum','Pod_types','M_app_grabage','GC_count','GC_time_avg','Oprate_avg','Mean_latency_avg','Median_latency_avg','95_pctile_avg','max_latency_avg','rows_read_write_request','errors_avg','App_crash_sum','SSH_failure_sum','TCP_flaw_sum','app_log_size_sum','new_syscall_emergence','Action'])

df.head()

,T_prem,T_gen,N_pot_t,M_kub_t,C_kub_t,N_pod_L,M_kub_L,C_kub_L,U_type,r,...,95_pctile_avg,max_latency_avg,rows_read_write_request,errors_avg,App_crash_sum,SSH_failure_sum,TCP_flaw_sum,app_log_size_sum,new_syscall_emergence,Action
0,120,300,0,0,0,15,30,8000,0,0,...,0,0,0,0,0,0,0,0,0,0
1,90,360,0,0,0,18,28,7500,0,0,...,0,0,0,0,0,0,0,0,0,0
2,100,400,0,0,0,20,20,7000,0,0,...,0,0,0,0,0,0,0,0,0,0
3,150,210,0,0,0,17,28,6500,0,0,...,0,0,0,0,0,0,0,0,0,0
4,180,380,0,0,0,24,20,7000,0,0,...,0,0,0,0,0,0,0,0,0,0